version: '3'
services:
  query-api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app  # Hot reload - mount toàn bộ code
      - C:/Users/User/.ssh/id_rsa:/root/.ssh/id_rsa:ro  # SSH key cho dev
      - query_results:/app/api/scripts/query_results  # Persistent volume cho query results
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=5000
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - USE_SSH_TUNNEL=true
      - SCHEDULER_ENABLED=true
    restart: unless-stopped

volumes:
  query_results:  # Volume để lưu kết quả query