version: '3'
services:
  query-api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=5000
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - USE_SSH_TUNNEL=false
      - SCHEDULER_ENABLED=true
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 